In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
%matplotlib inline
pd.set_option('display.max_columns', 100)

In [2]:
allPair = pd.read_csv("../data/allPair.csv",low_memory=False)

In [3]:
allPair.head()

,website_x,home_url,property_type,record_type,parser_type,latitude_x,longitude_x,streetaddr_x,city_x,state,zipcode,country,numbed,num_bath_full,num_bath_part,rentalprice_min,rentalprice_max,saleprice,yearbuilt,floor_plan,garage,lotsize,stories,size,pool,style,numofparking,gatedCommunity,stainlessAppliances,fireplace,floorType,kitchenCountertop,renovation,elevation,elevationType,description,crawl_time,datalisted,inactive,UniversityName,streetaddr_y,city_y,postcode,acceptanceRate,ranking,enroll,latitude_y,longitude_y,type,endowment,acadStaff,students,underGrad,postGrad,website_y,distance
0,http://www.trulia.com,http://www.trulia.com/property/3212474421-2454...,null,sale,null,32.546707,-117.08140,Tijuana River Valley San Diego County,San Diego,CA,92154,USA,-1,-1,-1,-1,-1,1500000,\N,NaN,\N,\N,\N,-1,0,single-family home,\N,0,0,0,\N,\N,0,8.45040,flat,an amazing opportunity to own valuable equestr...,2016-07-03 08:54:27,\N,\N,United States University,830 Bay Blvd,Chula Vista,91911,\N,\N,\N,32.617451,-117.092743,Private:for-profit,\N,50,650,\N,\N,http://www.usuniversity.edu,0.071648
1,http://www.trulia.com,http://www.trulia.com/foreclosure/27063855-313...,null,sale,null,32.547146,-117.05131,San Ysidro San Diego County,San Diego,CA,92173,USA,4,2,-1,-1,-1,0,2000,NaN,\N,\N,\N,1385,0,single-family home,2,0,0,0,\N,\N,0,16.63833,flat,this single-family home is located at 3135 wit...,2016-07-03 09:03:47,\N,\N,United States University,830 Bay Blvd,Chula Vista,91911,\N,\N,\N,32.617451,-117.092743,Private:for-profit,\N,50,650,\N,\N,http://www.usuniversity.edu,0.081606
2,http://www.trulia.com,http://www.trulia.com/property/3233806604-291-...,null,sale,null,32.549200,-117.04593,San Ysidro San Diego County,San Diego,CA,92173,USA,2,2,-1,-1,-1,168000,1996,NaN,\N,\N,\N,925,0,condo,\N,0,0,0,\N,\N,0,16.04365,flat,property needs tlc,2016-07-03 11:55:00,\N,\N,United States University,830 Bay Blvd,Chula Vista,91911,\N,\N,\N,32.617451,-117.092743,Private:for-profit,\N,50,650,\N,\N,http://www.usuniversity.edu,0.082763
3,http://www.trulia.com,http://www.trulia.com/foreclosure/3207083041-2...,null,sale,null,32.560734,-117.06074,San Ysidro San Diego County,San Diego,CA,92173,USA,2,2,-1,-1,-1,0,1986,NaN,\N,\N,\N,729,0,condo,\N,0,0,0,\N,\N,0,15.22638,flat,this condo is located at 2043 dairy mart road ...,2016-07-03 09:09:22,\N,\N,United States University,830 Bay Blvd,Chula Vista,91911,\N,\N,\N,32.617451,-117.092743,Private:for-profit,\N,50,650,\N,\N,http://www.usuniversity.edu,0.065123
4,http://www.trulia.com,http://www.trulia.com/foreclosure/3207084761-3...,null,sale,null,32.562336,-117.05700,San Ysidro San Diego County,San Diego,CA,92173,USA,4,2,-1,-1,-1,0,1979,NaN,\N,\N,\N,1238,0,single-family home,2,0,0,0,\N,\N,0,26.94564,flat,this single-family home is located at 3487 cor...,2016-07-03 09:09:26,\N,\N,United States University,830 Bay Blvd,Chula Vista,91911,\N,\N,\N,32.617451,-117.092743,Private:for-profit,\N,50,650,\N,\N,http://www.usuniversity.edu,0.065690

In [4]:
allPair.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149348 entries, 0 to 149347
Data columns (total 56 columns):
website_x              149348 non-null object
home_url               149343 non-null object
property_type          149348 non-null object
record_type            149348 non-null object
parser_type            149348 non-null object
latitude_x             149348 non-null float64
longitude_x            149348 non-null float64
streetaddr_x           149348 non-null object
city_x                 149348 non-null object
state                  149348 non-null object
zipcode                149348 non-null object
country                149348 non-null object
numbed                 149348 non-null int64
num_bath_full          149348 non-null int64
num_bath_part          149348 non-null int64
rentalprice_min        149348 non-null int64
rentalprice_max        149348 non-null int64
saleprice              149348 non-null int64
yearbuilt              149348 non-null object
floor_plan             0 non-null float64
garage                 149348 non-null object
lotsize                149348 non-null object
stories                149348 non-null object
size                   149348 non-null int64
pool                   149348 non-null int64
style                  149142 non-null object
numofparking           149348 non-null object
gatedCommunity         149348 non-null int64
stainlessAppliances    149348 non-null int64
fireplace              149348 non-null int64
floorType              149348 non-null object
kitchenCountertop      149348 non-null object
renovation             149348 non-null int64
elevation              149348 non-null object
elevationType          149348 non-null object
description            149348 non-null object
crawl_time             149348 non-null object
datalisted             149348 non-null object
inactive               149348 non-null object
UniversityName         149348 non-null object
streetaddr_y           149348 non-null object
city_y                 149348 non-null object
postcode               149348 non-null object
acceptanceRate         149348 non-null object
ranking                149348 non-null object
enroll                 149348 non-null object
latitude_y             149348 non-null float64
longitude_y            149348 non-null float64
type                   149348 non-null object
endowment              149348 non-null object
acadStaff              149348 non-null object
students               149348 non-null object
underGrad              149348 non-null object
postGrad               149348 non-null object
website_y              148454 non-null object
distance               149348 non-null float64
dtypes: float64(6), int64(12), object(38)
memory usage: 63.8+ MB

In [5]:
featList = list(allPair.columns.values)
type(featList)

list

In [6]:
f = open("../data/allPairFeat.csv", "w")
# f.write("feature" + "," + "dtype" + "\n")
for feature in featList:
    f.write(feature + ',' + str(allPair[feature].dtype) + '\n')
f.close()

In [7]:
ff = {}
with open("../data/allPairFeat.csv") as f:
    for line in f:
        feature, dtype = line.strip().split(",")
        ff[feature] = dtype
print ff

{'streetaddr_y': 'object', 'streetaddr_x': 'object', 'postGrad': 'object', 'num_bath_part': 'int64', 'longitude_y': 'float64', 'longitude_x': 'float64', 'numofparking': 'object', 'UniversityName': 'object', 'record_type': 'object', 'inactive': 'object', 'yearbuilt': 'object', 'postcode': 'object', 'website_y': 'object', 'elevationType': 'object', 'elevation': 'object', 'numbed': 'int64', 'endowment': 'object', 'size': 'int64', 'style': 'object', 'property_type': 'object', 'description': 'object', 'rentalprice_min': 'int64', 'zipcode': 'object', 'city_x': 'object', 'website_x': 'object', 'students': 'object', 'state': 'object', 'latitude_y': 'float64', 'acceptanceRate': 'object', 'home_url': 'object', 'type': 'object', 'ranking': 'object', 'underGrad': 'object', 'kitchenCountertop': 'object', 'rentalprice_max': 'int64', 'datalisted': 'object', 'parser_type': 'object', 'stainlessAppliances': 'int64', 'saleprice': 'int64', 'floorType': 'object', 'fireplace': 'int64', 'renovation': 'int64', 'pool': 'int64', 'latitude_x': 'float64', 'gatedCommunity': 'int64', 'distance': 'float64', 'enroll': 'object', 'floor_plan': 'float64', 'num_bath_full': 'int64', 'city_y': 'object', 'garage': 'object', 'stories': 'object', 'crawl_time': 'object', 'country': 'object', 'acadStaff': 'object', 'lotsize': 'object'}

In [8]:
# allPair2 = allPair.loc[allPair['zipcode'] != "\\N" & allPair['yearbuilt'] != "\\N"]
allPair2 = allPair.loc[allPair['zipcode'] != "\\N"]
allPair2 = allPair2.loc[allPair2['yearbuilt'] != "\\N"]

In [9]:
allPair2["zipcode"] = allPair2["zipcode"].astype(int)
allPair2["yearbuilt"] = allPair2["yearbuilt"].astype(int)
print allPair2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 62313 entries, 1 to 149347
Data columns (total 56 columns):
website_x              62313 non-null object
home_url               62309 non-null object
property_type          62313 non-null object
record_type            62313 non-null object
parser_type            62313 non-null object
latitude_x             62313 non-null float64
longitude_x            62313 non-null float64
streetaddr_x           62313 non-null object
city_x                 62313 non-null object
state                  62313 non-null object
zipcode                62313 non-null int64
country                62313 non-null object
numbed                 62313 non-null int64
num_bath_full          62313 non-null int64
num_bath_part          62313 non-null int64
rentalprice_min        62313 non-null int64
rentalprice_max        62313 non-null int64
saleprice              62313 non-null int64
yearbuilt              62313 non-null int64
floor_plan             0 non-null float64
garage                 62313 non-null object
lotsize                62313 non-null object
stories                62313 non-null object
size                   62313 non-null int64
pool                   62313 non-null int64
style                  62313 non-null object
numofparking           62313 non-null object
gatedCommunity         62313 non-null int64
stainlessAppliances    62313 non-null int64
fireplace              62313 non-null int64
floorType              62313 non-null object
kitchenCountertop      62313 non-null object
renovation             62313 non-null int64
elevation              62313 non-null object
elevationType          62313 non-null object
description            62313 non-null object
crawl_time             62313 non-null object
datalisted             62313 non-null object
inactive               62313 non-null object
UniversityName         62313 non-null object
streetaddr_y           62313 non-null object
city_y                 62313 non-null object
postcode               62313 non-null object
acceptanceRate         62313 non-null object
ranking                62313 non-null object
enroll                 62313 non-null object
latitude_y             62313 non-null float64
longitude_y            62313 non-null float64
type                   62313 non-null object
endowment              62313 non-null object
acadStaff              62313 non-null object
students               62313 non-null object
underGrad              62313 non-null object
postGrad               62313 non-null object
website_y              61632 non-null object
distance               62313 non-null float64
dtypes: float64(6), int64(14), object(36)
memory usage: 27.1+ MB
None

In [10]:
corr = allPair2.corr()
price_corr = corr["saleprice"]
price_corr = price_corr.to_dict()
# print price_corr
for ele in sorted(price_corr.items(), key = lambda x: -abs(x[1])):
    print("{0}: \t{1}".format(*ele))

size: 	0.297374740621
num_bath_part: 	0.0279425253669
rentalprice_max: 	nan
floor_plan: 	nan
saleprice: 	1.0
numbed: 	0.157614386118
zipcode: 	0.132943618201
num_bath_full: 	0.131698647337
longitude_y: 	-0.130572395001
longitude_x: 	-0.130334475356
fireplace: 	0.118881811208
pool: 	0.0883649810674
gatedCommunity: 	0.0671329907023
rentalprice_min: 	-0.0515775931241
yearbuilt: 	0.0398063079397
stainlessAppliances: 	0.03740223704
renovation: 	0.031757742325
latitude_y: 	0.00301283498839
latitude_x: 	0.0029158239669
distance: 	-0.00180301368065

In [11]:
CA = allPair2.loc[allPair["state"] == "CA"]

In [12]:
corr_CA = CA.corr()
price_corr = corr_CA["saleprice"]
price_corr = price_corr.to_dict()
# print price_corr
for ele in sorted(price_corr.items(), key = lambda x: -abs(x[1])):
    print("{0}: \t{1}".format(*ele))

size: 	0.471940732391
num_bath_part: 	0.0371042669825
rentalprice_max: 	nan
floor_plan: 	nan
saleprice: 	1.0
numbed: 	0.168489422083
pool: 	0.133481121338
fireplace: 	0.111100213367
gatedCommunity: 	0.108818369993
yearbuilt: 	0.0644088293331
num_bath_full: 	0.0605754289516
latitude_y: 	-0.0560398735269
distance: 	-0.0449807630584
stainlessAppliances: 	0.0442524061948
rentalprice_min: 	nan
renovation: 	0.0610763270649
zipcode: 	-0.0587218532035
latitude_x: 	-0.0566358910297
longitude_y: 	0.0122115678567
longitude_x: 	0.00662017779